const express = require('express');
const { getUser, getWalletForUser, rotateWallet, getUserHistory, updateProfile, getRanking, deleteUser, searchFreelancers } = require('../controllers/userController');
const { verifyToken } = require('../middleware/jwt');
const router = express.Router();
router.get('/ranking', getRanking);
router.get('/search/freelancers', searchFreelancers);
router.get('/:publicKey', getUser);
router.get('/:publicKey/wallet', verifyToken, getWalletForUser);
router.post('/:publicKey/wallet/rotate', verifyToken, rotateWallet);
router.get('/:publicKey/history', getUserHistory);
router.patch('/:publicKey', verifyToken, updateProfile);
router.delete('/:publicKey', verifyToken, deleteUser);
module.exports = router;